---
- name: Installs packages
  hosts: all 
  user: root
  tasks:
  - name: install list of packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - telnet
    - unzip
    - lftp
    - elinks
    - wget


