---
- name: add users
  hosts: all 
  user: root
  vars:
    users:
    - "ben"
    - "lisa"
    - "kate"
    - "dan"
    - "sam"
  tasks:
  - name: Create users
    user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      state: present
    with_items: "{{ users }}"